export const fieldNames = {
  INPUT_NAME: "inputName",
  IMAGE: "image",
  PROJECT_NAME: "projectName",
  PROJECT_WEBSITE: "projectWebsite",
  PROJECT_ACTIVITY_FIELD: "projectActivityField",
  PROJECT_IMAGE: "projectImage",
  MEMBERS_TYPE: "membersType",
  PROMOTION_CHANNELS_PLATFORMS: "platforms",
  PROMOTION_CHANNELS_SOCIAL_MEDIA: "socialMedia",
  PROMOTION_CHANNELS_OFFLINE_EVENTS: "offlineEvents",
  PROBLEMS_LIST: "problemsList",
  PROBLEMS_GOAL: "problemsGoal",
  PROBLEMS_PRIORITY: "problemsProirity",
  PAYMENT_NUMBER: "number",
  PAYMENT_EXPIRY: "expiry",
  PAYMENT_CVC: "cvc",
  PAYMENT_NAME: "name",
  PAYMENT_FOCUS: "focus",
} as const;
